---

# Due to a kind of regression with ansible 1.8, we need to check if the repo
# has already been cloned before clone it for the first (and only) time
# See: https://github.com/ansible/ansible-modules-core/issues/426

- name: clone check
  stat:
    path: /usr/local/share/oh-my-zsh
  register: result
  sudo: yes

- name: clone
  git: >
    repo=https://github.com/robbyrussell/oh-my-zsh.git
    dest=/usr/local/share/oh-my-zsh
  when: not result.stat.exists
  sudo: yes

- name: template users root
  template: >
    src=zshrc.j2
    dest=/root/.zshrc
  with_dict: elao_ohmyzsh_users
  when: item.key == 'root'
  sudo: yes

- name: template users
  template: >
    src=zshrc.j2
    dest=/home/{{ item.key }}/.zshrc
  with_dict: elao_ohmyzsh_users
  when: item.key != 'root'
  sudo: yes

- name: shell users
  user: >
    name={{ item.key }}
    shell=/bin/zsh
  with_dict: elao_ohmyzsh_users
  sudo: yes
